config/routes.rb
Rails.application.routes.draw do

  devise_for :users , controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :repos, only: [:index] do
    collection do
      get 'commits'
    end
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :validatable, :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    info = auth.info
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = info.email
      user.name = info.name
      user.password = Devise.friendly_token[0,20]
      user.profile_pic_url = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/github_api.rb
module GithubApi

  def github
    @github ||= Github.new oauth_token: session[:token]
  end

  def all_repos
    github.repos.list
  end

  def all_commits(repo, start_date, end_date)

    return [] if start_date.blank? && end_date.blank?

    opts = {user: session[:github_username], repo: repo}

    if start_date.present?
      opts[:since] = start_date.to_date.strftime('%Y-%m-%dT%H:%M:%SZ')
    end

    if end_date.present?
      opts[:until] = end_date.to_date.strftime('%Y-%m-%dT%H:%M:%SZ')
    end
    commits = github.repos.commits.list opts
    res = get_commits_filtered_data(commits)
  end

  private

    def get_commits_filtered_data(commits)
      out = []
      commits.each do|commit|
        commit_obj = {
          committer: committer_name(commit),
          message: message(commit),
          date: commit_date(commit),
          image_path: committer_image(commit)
        }
        out.push(commit_obj)
      end
      return out
    end

    def committer_name(commit)
      commit.commit.committer.name.titleize
    end

    def message(commit)
      commit.commit.message
    end

    def commit_date(commit)
      commit.commit.committer.date.to_datetime.strftime("%d %b %y %H:%M")
    end

    def committer_image(commit)
      commit.committer.avatar_url if commit.committer
    end

end

app/controllers/concerns/parsers.rb
module Parsers

  module Omniauth

    def omniauth_response
      request.env["omniauth.auth"]
    end

    def followers
      omniauth_response.extra.raw_info.followers
    end

    def token
      omniauth_response.credentials.token
    end

    def github_username
      omniauth_response.info.nickname
    end

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to repos_path
    else
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :authenticate_user!
  include GithubApi

  def index
    @repos = all_repos
  end

  def commits
    @repo = params[:repo]
    @commits = all_commits(params[:repo], params[:start], params[:end])
    gon.commits = @commits
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Parsers::Omniauth

  before_action :set_or_create_user, only: [:github]

  def github
    set_session
    sign_in @user
    set_flash_message(:notice, :success, kind: "Githib")
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end

  private

    def set_or_create_user
      @user = User.from_omniauth(omniauth_response)
      redirect_to root_path, flash: { error: @user.errors.full_messages } if @user.errors.any?
    end

    def set_session
      session[:id] = @user.id
      session[:email] = @user.email
      session[:name] = @user.name
      session[:github_username] = github_username
      session[:token] = token
      session[:followers] = followers
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash
    html = ""
    flash.each do |type, message|
      html << \
      if type.to_s == "alert"
        flash_single_alert_message(message)
      else
        flash_single_success_message(message)
      end
    end
    html.html_safe
  end

  private

  def flash_single_alert_message(message)
    content_tag :div, class: "flash alert alert-danger" do
      ( button_tag 'x', class: "close", data: {dismiss: "alert"} ) + message
    end
  end

  def flash_single_success_message(message)
    content_tag :div, class: "flash alert alert-success" do
      ( button_tag 'x', class: "close", data: {dismiss: "alert"} ) + message
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

  include UserHelper

  def profile_div()
    (content_tag :div, class: "profile-pic" do
      if current_user.profile_pic_url.present?
        (image_tag current_user.profile_pic_url, alt: "Profile Pic").to_s
      else
        (image_tag "default_profile_pic.png", alt: "Profile Pic").to_s
      end
    end).html_safe
  end

end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/user_helper.rb
module UserHelper

  def name
    current_user.name.titleize
  end

  def followers
    session[:followers]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Chamber</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= nav_bar inverse: true, fixed: :top, responsive: true, brand: "Application", brand_link: "#" do%>
      <% if current_user %>
      <%= menu_group :pull => :right do %>
        <p class="navbar-text">Signed in as <b><%= current_user.email %></b></p><%= menu_item "Log Out", destroy_user_session_path, :method => :delete %>
      <%end%>
      <% end %>
    <%end%>
    <div class="container">
      <div class="row">
          <div class="col-md-12">
            <%= display_flash %>
            <div class="col-md-3">
              <%= render 'shared/profile' %>
            </div>
            <div class="col-md-9">
              <%= yield %>
            </div>
          </div>
      </div>
    </div>
    <%= yield :javascript_includes %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviceBootstrapCancan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= nav_bar inverse: true, fixed: :top, responsive: true, brand: "Application", brand_link: "#" %>
    <div class="container">
      <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <%= display_flash %>
            <%= yield %>
          </div>
          <div class="col-md-3"></div>
      </div>
    </div>
  </body>
</html>

app/views/repos/_commits_table.html.erb
<div class="table-responsive commits-table">
  <table class="table">
    <thead>
      <tr>
        <th class="col-md-1">#</th>
        <th class="col-md-3">Commiter</th>
        <th class="col-md-6">Message</th>
        <th class="col-md-2">Date</th>
      </tr>
    </thead>
    <tbody>
    <% @commits.each_with_index do|commit, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= commit[:committer] %></td>
        <td><%= commit[:message] %></td>
        <td><%= commit[:date] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/repos/commits.html.erb
<%= Gon::Base.render_data %>
<%= link_to (content_tag(:span, "", class: "glyphicon glyphicon-circle-arrow-left")).to_s + " All repos", repos_path, class: "back-link" %>
<h2>Repo: <%= @repo %></h2>
<div class="date-filter">
  <form method="get" accept-charset="utf-8">
    <input type="hidden" name="repo" value="<%= @repo %>">
    <div class="col-md-5">
        <div class="col-md-4">
          <label class="mt10">Start Date: </label>
        </div>
        <div class="col-md-8">
          <input class="form-control start-date" name="start" type="text" readonly placeholder="yyyy/mm/dd" required>
        </div>
    </div>
    <div class="col-md-5">
      <div class="col-md-4">
        <label class="mt10">End Date: </label>
      </div>
      <div class="col-md-8">
        <input class="form-control end-date" name="end" type="text" readonly placeholder="yyyy/mm/dd" required>
      </div>
    </div>
    <div class="col-md-2">
      <button type="submit" class="btn btn-primary">Get Commits</button>
    </div>
  </form>
</div>
<div id="timeline1"></div>
<% if @commits && @commits.any? %>
  <%= render 'commits_table'%>
<%end%>
<% content_for :javascript_includes do%>
  <%= javascript_include_tag 'lib/d3.v2.min', 'lib/timeknots-min', 'repos'%>
<%end%>

app/views/repos/index.html.erb
<h2>Repositories</h2>
<div class="repos mt20">
<% @repos.each do|repo| %>
  <div class="panel-group">
    <div class="panel panel-info">
      <div class="panel-heading">
        <%= repo.name %>
        <!-- <button type="button" class="btn btn-link pull-right">Commit History</button> -->
        <%= link_to "Commit History", commits_repos_path(repo: repo.name), class: "btn btn-link pull-right" %>
      </div>
      <div class="panel-body"> <%= repo.description %></div>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_profile.html.erb
<%= profile_div %>
<div class="name"><%= name %></div>
<h5><span class="glyphicon glyphicon-user"></span> Followers <span class="badge badge-secondary"><%= followers %></span></h5>